using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JAMENDOwnloader
{
    public class ID3Genre
    {
        public Dictionary<Byte, String> ID3;

        #region Genre
        public ID3Genre ()
        {
            ID3 = new Dictionary<Byte,String>();
            ID3.Add(00,"Blues");
            ID3.Add(01,"Classic Rock");
            ID3.Add(02,"Country");
            ID3.Add(03,"Dance");
            ID3.Add(04,"Disco");
            ID3.Add(05,"Funk");
            ID3.Add(06,"Grunge");
            ID3.Add(07,"Hip-Hop");
            ID3.Add(08,"Jazz");
            ID3.Add(09,"Metal");
            ID3.Add(10,"New Age");
            ID3.Add(11,"Oldies");
            ID3.Add(12,"Other");
            ID3.Add(13,"Pop");
            ID3.Add(14,"Rhythm and Blues");
            ID3.Add(15,"Rap");
            ID3.Add(16,"Reggae");
            ID3.Add(17,"Rock");
            ID3.Add(18,"Techno");
            ID3.Add(19,"Industrial");
            ID3.Add(20,"Alternative");
            ID3.Add(21,"Ska");
            ID3.Add(22,"Death Metal");
            ID3.Add(23,"Pranks");
            ID3.Add(24,"Soundtrack");
            ID3.Add(25,"Euro-Techno");
            ID3.Add(26,"Ambient");
            ID3.Add(27,"Trip-Hop");
            ID3.Add(28,"Vocal");
            ID3.Add(29,"Jazz&Funk");
            ID3.Add(30,"Fusion");
            ID3.Add(31,"Trance");
            ID3.Add(32,"Classical");
            ID3.Add(33,"Instrumental");
            ID3.Add(34,"Acid");
            ID3.Add(35,"House");
            ID3.Add(36,"Game");
            ID3.Add(37,"Sound Clip");
            ID3.Add(38,"Gospel");
            ID3.Add(39,"Noise");
            ID3.Add(40,"Alternative Rock");
            ID3.Add(41,"Bass");
            ID3.Add(42,"Soul");
            ID3.Add(43,"Punk");
            ID3.Add(44,"Space");
            ID3.Add(45,"Meditative");
            ID3.Add(46,"Instrumental Pop");
            ID3.Add(47,"Instrumental Rock");
            ID3.Add(48,"Ethnic");
            ID3.Add(49,"Gothic");
            ID3.Add(50,"Darkwave");
            ID3.Add(51,"Techno-Industrial");
            ID3.Add(52,"Electronic");
            ID3.Add(53,"Pop-Folk");
            ID3.Add(54,"Eurodance");
            ID3.Add(55,"Dream");
            ID3.Add(56,"Southern Rock");
            ID3.Add(57,"Comedy");
            ID3.Add(58,"Cult");
            ID3.Add(59,"Gangsta");
            ID3.Add(60,"Top 40");
            ID3.Add(61,"Christian Rap");
            ID3.Add(62,"Pop/Funk");
            ID3.Add(63,"Jungle");
            ID3.Add(64,"Native US");
            ID3.Add(65,"Cabaret");
            ID3.Add(66,"New Wave");
            ID3.Add(67,"Psychedelic");
            ID3.Add(68,"Rave");
            ID3.Add(69,"Showtunes");
            ID3.Add(70,"Trailer");
            ID3.Add(71,"Lo-Fi");
            ID3.Add(72,"Tribal");
            ID3.Add(73,"Acid Punk");
            ID3.Add(74,"Acid Jazz");
            ID3.Add(75,"Polka");
            ID3.Add(76,"Retro");
            ID3.Add(77,"Musical");
            ID3.Add(78,"Rock & Roll");
            ID3.Add(79,"Hard Rock");
            ID3.Add(80,"Folk");
            ID3.Add(81,"Folk-Rock");
            ID3.Add(82,"National Folk");
            ID3.Add(83,"Swing");
            ID3.Add(84,"Fast Fusion");
            ID3.Add(85,"Bebob");
            ID3.Add(86,"Latin");
            ID3.Add(87,"Revival");
            ID3.Add(88,"Celtic");
            ID3.Add(89,"Bluegrass");
            ID3.Add(90,"Avantgarde");
            ID3.Add(91,"Gothic Rock");
            ID3.Add(92,"Progressive Rock");
            ID3.Add(93,"Psychedelic Rock");
            ID3.Add(94,"Symphonic Rock");
            ID3.Add(95,"Slow Rock");
            ID3.Add(96,"Big Band");
            ID3.Add(97,"Chorus");
            ID3.Add(98,"Easy Listening");
            ID3.Add(99,"Acoustic");
            ID3.Add(100,"Humour");
            ID3.Add(101,"Speech");
            ID3.Add(102,"Chanson");
            ID3.Add(103,"Opera");
            ID3.Add(104,"Chamber Music");
            ID3.Add(105,"Sonata");
            ID3.Add(106,"Symphony");
            ID3.Add(107,"Booty Bass");
            ID3.Add(108,"Primus");
            ID3.Add(109,"Porn Groove");
            ID3.Add(110,"Satire");
            ID3.Add(111,"Slow Jam");
            ID3.Add(112,"Club");
            ID3.Add(113,"Tango");
            ID3.Add(114,"Samba");
            ID3.Add(115,"Folklore");
            ID3.Add(116,"Ballad");
            ID3.Add(117,"Power Ballad");
            ID3.Add(118,"Rhythmic Soul");
            ID3.Add(119,"Freestyle");
            ID3.Add(120,"Duet");
            ID3.Add(121,"Punk Rock");
            ID3.Add(122,"Drum Solo");
            ID3.Add(123,"A capella");
            ID3.Add(124,"Euro-House");
            ID3.Add(125,"Dance Hall");
            ID3.Add(126,"Goa");
            ID3.Add(127,"Drum & Bass");
            ID3.Add(128,"Club-House");
            ID3.Add(129,"Hardcore");
            ID3.Add(130,"Terror");
            ID3.Add(131,"Indie");
            ID3.Add(132,"BritPop");
            ID3.Add(133,"Negerpunk");
            ID3.Add(134,"Polsk Punk");
            ID3.Add(135,"Beat");
            ID3.Add(136,"Christian Gangsta Rap");
            ID3.Add(137,"Heavy Metal");
            ID3.Add(138,"Black Metal");
            ID3.Add(139,"Crossover");
            ID3.Add(140,"Contemporary Christian");
            ID3.Add(141,"Christian Rock");
            ID3.Add(142,"Merengue");
            ID3.Add(143,"Salsa");
            ID3.Add(144,"Thrash Metal");
            ID3.Add(145,"Anime");
            ID3.Add(146,"Jpop");
            ID3.Add(147,"Synthpop");
        }
        #endregion

    }
}
